//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiimoteTest.WiiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="WiiService.IWiiTransfer")]
    public interface IWiiTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteData", ReplyAction="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteDataResponse")]
        void SendWiimoteData(WiimoteLib.Point3 wiidata);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteData", ReplyAction="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteDataResponse")]
        System.IAsyncResult BeginSendWiimoteData(WiimoteLib.Point3 wiidata, System.AsyncCallback callback, object asyncState);
        
        void EndSendWiimoteData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWiiTransferChannel : WiimoteTest.WiiService.IWiiTransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WiiTransferClient : System.ServiceModel.ClientBase<WiimoteTest.WiiService.IWiiTransfer>, WiimoteTest.WiiService.IWiiTransfer {
        
        private BeginOperationDelegate onBeginSendWiimoteDataDelegate;
        
        private EndOperationDelegate onEndSendWiimoteDataDelegate;
        
        private System.Threading.SendOrPostCallback onSendWiimoteDataCompletedDelegate;
        
        public WiiTransferClient() {
        }
        
        public WiiTransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WiiTransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WiiTransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WiiTransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendWiimoteDataCompleted;
        
        public void SendWiimoteData(WiimoteLib.Point3 wiidata) {
            base.Channel.SendWiimoteData(wiidata);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendWiimoteData(WiimoteLib.Point3 wiidata, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendWiimoteData(wiidata, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSendWiimoteData(System.IAsyncResult result) {
            base.Channel.EndSendWiimoteData(result);
        }
        
        private System.IAsyncResult OnBeginSendWiimoteData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WiimoteLib.Point3 wiidata = ((WiimoteLib.Point3)(inValues[0]));
            return this.BeginSendWiimoteData(wiidata, callback, asyncState);
        }
        
        private object[] OnEndSendWiimoteData(System.IAsyncResult result) {
            this.EndSendWiimoteData(result);
            return null;
        }
        
        private void OnSendWiimoteDataCompleted(object state) {
            if ((this.SendWiimoteDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendWiimoteDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendWiimoteDataAsync(WiimoteLib.Point3 wiidata) {
            this.SendWiimoteDataAsync(wiidata, null);
        }
        
        public void SendWiimoteDataAsync(WiimoteLib.Point3 wiidata, object userState) {
            if ((this.onBeginSendWiimoteDataDelegate == null)) {
                this.onBeginSendWiimoteDataDelegate = new BeginOperationDelegate(this.OnBeginSendWiimoteData);
            }
            if ((this.onEndSendWiimoteDataDelegate == null)) {
                this.onEndSendWiimoteDataDelegate = new EndOperationDelegate(this.OnEndSendWiimoteData);
            }
            if ((this.onSendWiimoteDataCompletedDelegate == null)) {
                this.onSendWiimoteDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendWiimoteDataCompleted);
            }
            base.InvokeAsync(this.onBeginSendWiimoteDataDelegate, new object[] {
                        wiidata}, this.onEndSendWiimoteDataDelegate, this.onSendWiimoteDataCompletedDelegate, userState);
        }
    }
}
