//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiimoteTest.WiiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignalSample", Namespace="http://schemas.datacontract.org/2004/07/WiimoteTest")]
    [System.SerializableAttribute()]
    public partial class SignalSample : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WiimoteLib.Point3 sampleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime sampleTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WiimoteLib.Point3 sample {
            get {
                return this.sampleField;
            }
            set {
                if ((this.sampleField.Equals(value) != true)) {
                    this.sampleField = value;
                    this.RaisePropertyChanged("sample");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime sampleTimeStamp {
            get {
                return this.sampleTimeStampField;
            }
            set {
                if ((this.sampleTimeStampField.Equals(value) != true)) {
                    this.sampleTimeStampField = value;
                    this.RaisePropertyChanged("sampleTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="WiiService.IWiiTransfer")]
    public interface IWiiTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteData", ReplyAction="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteDataResponse")]
        void SendWiimoteData(System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteData", ReplyAction="http://Microsoft.ServiceModel.Samples/IWiiTransfer/SendWiimoteDataResponse")]
        System.IAsyncResult BeginSendWiimoteData(System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata, System.AsyncCallback callback, object asyncState);
        
        void EndSendWiimoteData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWiiTransferChannel : WiimoteTest.WiiService.IWiiTransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WiiTransferClient : System.ServiceModel.ClientBase<WiimoteTest.WiiService.IWiiTransfer>, WiimoteTest.WiiService.IWiiTransfer {
        
        private BeginOperationDelegate onBeginSendWiimoteDataDelegate;
        
        private EndOperationDelegate onEndSendWiimoteDataDelegate;
        
        private System.Threading.SendOrPostCallback onSendWiimoteDataCompletedDelegate;
        
        public WiiTransferClient() {
        }
        
        public WiiTransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WiiTransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WiiTransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WiiTransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendWiimoteDataCompleted;
        
        public void SendWiimoteData(System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata) {
            base.Channel.SendWiimoteData(wiidata);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendWiimoteData(System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendWiimoteData(wiidata, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSendWiimoteData(System.IAsyncResult result) {
            base.Channel.EndSendWiimoteData(result);
        }
        
        private System.IAsyncResult OnBeginSendWiimoteData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata = ((System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample>)(inValues[0]));
            return this.BeginSendWiimoteData(wiidata, callback, asyncState);
        }
        
        private object[] OnEndSendWiimoteData(System.IAsyncResult result) {
            this.EndSendWiimoteData(result);
            return null;
        }
        
        private void OnSendWiimoteDataCompleted(object state) {
            if ((this.SendWiimoteDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendWiimoteDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendWiimoteDataAsync(System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata) {
            this.SendWiimoteDataAsync(wiidata, null);
        }
        
        public void SendWiimoteDataAsync(System.Collections.Generic.List<WiimoteTest.WiiService.SignalSample> wiidata, object userState) {
            if ((this.onBeginSendWiimoteDataDelegate == null)) {
                this.onBeginSendWiimoteDataDelegate = new BeginOperationDelegate(this.OnBeginSendWiimoteData);
            }
            if ((this.onEndSendWiimoteDataDelegate == null)) {
                this.onEndSendWiimoteDataDelegate = new EndOperationDelegate(this.OnEndSendWiimoteData);
            }
            if ((this.onSendWiimoteDataCompletedDelegate == null)) {
                this.onSendWiimoteDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendWiimoteDataCompleted);
            }
            base.InvokeAsync(this.onBeginSendWiimoteDataDelegate, new object[] {
                        wiidata}, this.onEndSendWiimoteDataDelegate, this.onSendWiimoteDataCompletedDelegate, userState);
        }
    }
}
